### ISSUE TITLE
Feature request: Ports and links in the overview

### ISSUE THREAD

**Issue by curana** [laurensk/Dockmon#3]
Hi,

Thanks for this handy tool!

I have a suggestion though:
- add the ports mapping (like in portainer) as links to directly access the nodes services
- show the assigned IPs

Thanks!

**Comment by laurensk** [comment]
Hi @curana,

thanks for reaching out. Since this project is no longer actively maintained and I've no longer access to a production Docker environment, I can't implement those changes for myself. This should not stop anyone from implementing it, the API documentation for Portainer is really awesome and I've already implemented an easy to use API service in the app.

Thank you for your understanding!
