### ISSUE TITLE
Nothing is shown after logging in

### ISSUE THREAD

**Issue by devantler** [laurensk/Dockmon#4]
![80319A49-4BC4-4743-A581-70645BD0C539](https://user-images.githubusercontent.com/26203420/148434295-027629af-8897-494f-ae15-869568d5f16a.png)

After logging in nothing is shown. If i type incorrect user and password it does not authenticate so I think it is untelated to the login process. I am running the current version of the Business Edition.

**Comment by devantler** [comment]
Never mind. I just saw the project is no longer maintained, which is probably why I am having issues.

Best of luck!

**Comment by laurensk** [comment]
Hey @niem94, since I'm not any longer actively maintaining this project, there might have been API changes to the Portainer API which aren't reflected in the app.

If you got time, you can download the project and find out which requests don't work and fix them, I'd gladly accept pull requests.

All the best,
Laurens
